"""sync core schema with current models

Revision ID: 93cd0a90c897
Revises: bb6a005fe34c
Create Date: 2026-09-03 08:44:17.891899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "93cd0a90c897"
down_revision: Union[str, Sequence[str], None] = "bb6a005fe34c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('instructor', 'admin')", name="ck_users_role"),
        sa.PrimaryKeyConstraint("id"),
        schema="core",
    )
    op.create_index(
        op.f("ix_core_users_email"), "users", ["email"], unique=True, schema="core"
    )
    op.create_table(
        "generation_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("requested_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'generating', 'completed', 'failed')",
            name="ck_generation_requests_status",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["core.users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="core",
    )
    op.create_table(
        "generation_artifacts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("draft", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("model_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("review_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "review_status IN ('pending', 'applied', 'discarded')",
            name="ck_generation_artifacts_review_status",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["core.generation_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="core",
    )
    op.create_table(
        "assignments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("artifact_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "problem_statement", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("difficulty", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "difficulty IN ('easy', 'medium', 'hard')", name="ck_assignments_difficulty"
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["core.generation_artifacts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id"),
        schema="core",
    )
    op.create_table(
        "test_cases",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("assignment_id", sa.BigInteger(), nullable=False),
        sa.Column("input_data", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "expected_output", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["core.assignments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="core",
    )
    op.add_column(
        "knowledge_documents",
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        schema="core",
    )
    op.add_column(
        "knowledge_documents",
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        schema="core",
    )
    op.add_column(
        "knowledge_documents",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        schema="core",
    )
    op.add_column(
        "knowledge_documents",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        schema="core",
    )
    op.add_column(
        "knowledge_documents",
        sa.Column("uploaded_by", sa.BigInteger(), nullable=True),
        schema="core",
    )
    op.drop_constraint(
        op.f("knowledge_documents_r2_object_key_key"),
        "knowledge_documents",
        schema="core",
        type_="unique",
    )
    op.create_index(
        op.f("ix_core_knowledge_documents_r2_object_key"),
        "knowledge_documents",
        ["r2_object_key"],
        unique=True,
        schema="core",
    )
    op.create_foreign_key(
        None,
        "knowledge_documents",
        "users",
        ["uploaded_by"],
        ["id"],
        source_schema="core",
        referent_schema="core",
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        "ck_knowledge_documents_status",
        "knowledge_documents",
        "status IN ('uploaded', 'ingesting', 'ready', 'failed')",
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_knowledge_documents_status",
        "knowledge_documents",
        schema="core",
        type_="check",
    )
    op.drop_constraint(None, "knowledge_documents", schema="core", type_="foreignkey")
    op.drop_index(
        op.f("ix_core_knowledge_documents_r2_object_key"),
        table_name="knowledge_documents",
        schema="core",
    )
    op.create_unique_constraint(
        op.f("knowledge_documents_r2_object_key_key"),
        "knowledge_documents",
        ["r2_object_key"],
        schema="core",
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("knowledge_documents", "uploaded_by", schema="core")
    op.drop_column("knowledge_documents", "metadata", schema="core")
    op.drop_column("knowledge_documents", "status", schema="core")
    op.drop_column("knowledge_documents", "content_hash", schema="core")
    op.drop_column("knowledge_documents", "filename", schema="core")
    op.drop_table("test_cases", schema="core")
    op.drop_table("assignments", schema="core")
    op.drop_table("generation_artifacts", schema="core")
    op.drop_table("generation_requests", schema="core")
    op.drop_index(op.f("ix_core_users_email"), table_name="users", schema="core")
    op.drop_table("users", schema="core")
    # ### end Alembic commands ###
