"""OPS-15 classroom schema

Revision ID: c4e8a2f17b90
Revises: d3b7c1e9a204
Create Date: 2026-10-01 00:00:00.000000

ADR-0007 "Schema changes for the Phase 3 OPS task" as amended by ADR-0008:
accounts and sessions, Classrooms and Members, Assignment Versions and
Postings, Submissions and their test results, Notifications, Drafts and the
generation log behind the daily Quota, and the single-row AI settings.

Written by hand, never autogenerated. It does not touch the schemas, the
vector extension or the HNSW index, which earlier revisions own.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4e8a2f17b90"
down_revision: Union[str, Sequence[str], None] = "d3b7c1e9a204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SCHEMA = "core"


def _id() -> sa.Column:
    return sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False)


def _now(name: str) -> sa.Column:
    return sa.Column(
        name,
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False,
    )


def _at(name: str, *, nullable: bool) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), nullable=nullable)


def _fk(name: str, target: str, *, ondelete: str, nullable: bool = False):
    return sa.Column(
        name,
        sa.BigInteger(),
        sa.ForeignKey(f"{SCHEMA}.{target}", ondelete=ondelete),
        nullable=nullable,
    )


def _bigint_array(name: str) -> sa.Column:
    return sa.Column(
        name,
        postgresql.ARRAY(sa.BigInteger()),
        server_default=sa.text("'{}'::bigint[]"),
        nullable=False,
    )


def _jsonb(name: str, default: str) -> sa.Column:
    return sa.Column(
        name,
        postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text(f"'{default}'::jsonb"),
        nullable=False,
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ---- users -------------------------------------------------------------
    op.drop_constraint("ck_users_role", "users", schema=SCHEMA, type_="check")
    op.create_check_constraint(
        "ck_users_role",
        "users",
        "role IN ('student', 'instructor', 'admin')",
        schema=SCHEMA,
    )
    op.alter_column(
        "users", "role", server_default="student", schema=SCHEMA
    )
    op.alter_column(
        "users",
        "display_name",
        new_column_name="full_name",
        type_=sa.String(length=120),
        nullable=False,
        schema=SCHEMA,
    )
    op.add_column(
        "users", sa.Column("password_hash", sa.Text(), nullable=False), schema=SCHEMA
    )
    op.add_column("users", _at("email_verified_at", nullable=True), schema=SCHEMA)
    op.add_column(
        "users",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        schema=SCHEMA,
    )
    op.add_column("users", _at("last_active_at", nullable=True), schema=SCHEMA)

    op.create_table(
        "email_verification_tokens",
        _id(),
        _fk("user_id", "users.id", ondelete="CASCADE"),
        sa.Column("token_hash", sa.String(), nullable=False),
        _at("expires_at", nullable=False),
        _at("used_at", nullable=True),
        _now("created_at"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
        schema=SCHEMA,
    )
    op.create_table(
        "sessions",
        _id(),
        _fk("user_id", "users.id", ondelete="CASCADE"),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("csrf_token", sa.String(), nullable=False),
        _at("expires_at", nullable=False),
        _at("revoked_at", nullable=True),
        _now("created_at"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
        schema=SCHEMA,
    )
    op.create_table(
        "instructor_requests",
        _id(),
        _fk("user_id", "users.id", ondelete="CASCADE"),
        sa.Column("faculty", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        _now("requested_at"),
        _fk("reviewed_by", "users.id", ondelete="SET NULL", nullable=True),
        _at("reviewed_at", nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name="ck_instructor_requests_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )

    # ---- classrooms --------------------------------------------------------
    op.create_table(
        "classrooms",
        _id(),
        _fk("instructor_id", "users.id", ondelete="RESTRICT"),
        sa.Column("course_code", sa.String(), nullable=False),
        sa.Column("course_name", sa.String(), nullable=False),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("semester", sa.String(), nullable=False),
        sa.Column("join_code", sa.String(), nullable=True),
        _at("archived_at", nullable=True),
        _now("created_at"),
        _now("updated_at"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("join_code"),
        schema=SCHEMA,
    )
    op.create_table(
        "classroom_members",
        _id(),
        _fk("classroom_id", "classrooms.id", ondelete="CASCADE"),
        _fk("student_id", "users.id", ondelete="CASCADE"),
        _at("joined_at", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "classroom_id", "student_id", name="uq_classroom_members_pair"
        ),
        schema=SCHEMA,
    )

    # ---- assignments, versions, test cases, postings -----------------------
    op.add_column(
        "assignments",
        _fk("topic_id", "topics.id", ondelete="SET NULL", nullable=True),
        schema=SCHEMA,
    )
    op.add_column(
        "assignments",
        _fk("owner_id", "users.id", ondelete="SET NULL", nullable=True),
        schema=SCHEMA,
    )
    op.add_column(
        "assignments",
        sa.Column(
            "current_version",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        schema=SCHEMA,
    )
    op.add_column(
        "assignments",
        sa.Column(
            "time_limit_ms",
            sa.Integer(),
            server_default=sa.text("1000"),
            nullable=False,
        ),
        schema=SCHEMA,
    )
    op.add_column(
        "assignments",
        sa.Column("language", sa.String(), server_default="python3", nullable=False),
        schema=SCHEMA,
    )
    op.add_column(
        "assignments",
        sa.Column(
            "show_hidden_names",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        schema=SCHEMA,
    )

    op.create_table(
        "assignment_versions",
        _id(),
        _fk("assignment_id", "assignments.id", ondelete="CASCADE"),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("problem_statement", sa.String(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        _jsonb("test_cases", "[]"),
        sa.Column("time_limit_ms", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("show_hidden_names", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        _now("created_at"),
        sa.CheckConstraint(
            "difficulty IN ('easy', 'medium', 'hard')",
            name="ck_assignment_versions_difficulty",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "assignment_id", "number", name="uq_assignment_versions_number"
        ),
        schema=SCHEMA,
    )

    op.add_column(
        "test_cases",
        sa.Column("kind", sa.String(), server_default="sample", nullable=False),
        schema=SCHEMA,
    )
    op.add_column(
        "test_cases", sa.Column("note", sa.Text(), nullable=True), schema=SCHEMA
    )
    op.execute("UPDATE core.test_cases SET kind = 'hidden' WHERE is_hidden")
    op.create_check_constraint(
        "ck_test_cases_kind",
        "test_cases",
        "kind IN ('sample', 'hidden', 'edge')",
        schema=SCHEMA,
    )
    op.drop_column("test_cases", "is_hidden", schema=SCHEMA)

    op.create_table(
        "classroom_assignments",
        _id(),
        _fk("classroom_id", "classrooms.id", ondelete="CASCADE"),
        _fk("assignment_id", "assignments.id", ondelete="CASCADE"),
        _at("deadline", nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("allow_late", sa.Boolean(), nullable=False),
        sa.Column("allow_resubmission", sa.Boolean(), nullable=False),
        _at("published_at", nullable=False),
        _at("closed_at", nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "classroom_id", "assignment_id", name="uq_classroom_assignments_pair"
        ),
        schema=SCHEMA,
    )

    # ---- submissions -------------------------------------------------------
    op.create_table(
        "submissions",
        _id(),
        _fk("posting_id", "classroom_assignments.id", ondelete="CASCADE"),
        _fk("student_id", "users.id", ondelete="CASCADE"),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        _at("submitted_at", nullable=False),
        sa.Column("is_late", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "posting_id", "student_id", "attempt", name="uq_submissions_attempt"
        ),
        schema=SCHEMA,
    )
    op.create_table(
        "submission_test_results",
        _id(),
        _fk("submission_id", "submissions.id", ondelete="CASCADE"),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("verdict", sa.String(), nullable=False),
        sa.Column("time_seconds", sa.Float(), nullable=False),
        sa.Column("expected_output", sa.Text(), nullable=False),
        sa.Column("actual_output", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('sample', 'hidden', 'edge')",
            name="ck_submission_test_results_kind",
        ),
        sa.CheckConstraint(
            "verdict IN ('passed', 'wrong_answer', 'time_limit', 'runtime_error')",
            name="ck_submission_test_results_verdict",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "submission_id", "position", name="uq_submission_test_results_position"
        ),
        schema=SCHEMA,
    )

    # ---- notifications -----------------------------------------------------
    op.create_table(
        "notifications",
        _id(),
        _fk("user_id", "users.id", ondelete="CASCADE"),
        sa.Column("kind", sa.String(), nullable=False),
        _jsonb("payload", "{}"),
        _now("created_at"),
        _at("read_at", nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )

    # ---- generation --------------------------------------------------------
    op.drop_constraint(
        "generation_requests_requested_by_fkey",
        "generation_requests",
        schema=SCHEMA,
        type_="foreignkey",
    )
    op.alter_column(
        "generation_requests", "requested_by", nullable=False, schema=SCHEMA
    )
    op.create_foreign_key(
        "generation_requests_requested_by_fkey",
        "generation_requests",
        "users",
        ["requested_by"],
        ["id"],
        source_schema=SCHEMA,
        referent_schema=SCHEMA,
        ondelete="RESTRICT",
    )
    op.add_column(
        "generation_requests",
        _fk("classroom_id", "classrooms.id", ondelete="CASCADE"),
        schema=SCHEMA,
    )
    op.add_column(
        "generation_requests", _bigint_array("document_ids"), schema=SCHEMA
    )

    op.create_table(
        "drafts",
        _id(),
        _fk("classroom_id", "classrooms.id", ondelete="CASCADE"),
        _fk("requested_by", "users.id", ondelete="CASCADE"),
        sa.Column("prompt", sa.Text(), nullable=False),
        _jsonb("content", "{}"),
        _jsonb("citations", "[]"),
        _jsonb("settings", "{}"),
        _bigint_array("document_ids"),
        _bigint_array("classroom_ids"),
        sa.Column("status", sa.String(), server_default="reviewing", nullable=False),
        _fk("assignment_id", "assignments.id", ondelete="SET NULL", nullable=True),
        _at("generated_at", nullable=False),
        _now("created_at"),
        _now("updated_at"),
        sa.CheckConstraint(
            "status IN ('reviewing', 'published')", name="ck_drafts_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )
    op.create_table(
        "generation_events",
        _id(),
        _fk("user_id", "users.id", ondelete="CASCADE"),
        _at("occurred_at", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_generation_events_user_occurred",
        "generation_events",
        ["user_id", "occurred_at"],
        schema=SCHEMA,
    )

    op.create_table(
        "ai_settings",
        sa.Column(
            "id", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("daily_quota", sa.Integer(), nullable=False),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column("require_citations", sa.Boolean(), nullable=False),
        _now("updated_at"),
        sa.CheckConstraint("id = 1", name="ck_ai_settings_single_row"),
        sa.CheckConstraint("daily_quota > 0", name="ck_ai_settings_daily_quota"),
        sa.CheckConstraint("max_pages > 0", name="ck_ai_settings_max_pages"),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )
    op.execute(
        "INSERT INTO core.ai_settings "
        "(id, provider, model, daily_quota, max_pages, require_citations) "
        "VALUES (1, 'gemini', 'gemini-3.5-flash', 20, 50, true)"
    )

    # ---- knowledge documents -----------------------------------------------
    # uploaded_by stays nullable until CORE-16 (ADR-0008).
    op.add_column(
        "knowledge_documents",
        sa.Column("page_count", sa.Integer(), nullable=True),
        schema=SCHEMA,
    )
    op.add_column(
        "knowledge_documents",
        sa.Column(
            "progress", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        schema=SCHEMA,
    )
    op.add_column(
        "knowledge_documents",
        sa.Column("error_code", sa.String(), nullable=True),
        schema=SCHEMA,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("knowledge_documents", "error_code", schema=SCHEMA)
    op.drop_column("knowledge_documents", "progress", schema=SCHEMA)
    op.drop_column("knowledge_documents", "page_count", schema=SCHEMA)

    op.drop_table("ai_settings", schema=SCHEMA)
    op.drop_index(
        "ix_generation_events_user_occurred", "generation_events", schema=SCHEMA
    )
    op.drop_table("generation_events", schema=SCHEMA)
    op.drop_table("drafts", schema=SCHEMA)

    op.drop_column("generation_requests", "document_ids", schema=SCHEMA)
    op.drop_column("generation_requests", "classroom_id", schema=SCHEMA)
    op.drop_constraint(
        "generation_requests_requested_by_fkey",
        "generation_requests",
        schema=SCHEMA,
        type_="foreignkey",
    )
    op.alter_column(
        "generation_requests", "requested_by", nullable=True, schema=SCHEMA
    )
    op.create_foreign_key(
        "generation_requests_requested_by_fkey",
        "generation_requests",
        "users",
        ["requested_by"],
        ["id"],
        source_schema=SCHEMA,
        referent_schema=SCHEMA,
        ondelete="SET NULL",
    )

    op.drop_table("notifications", schema=SCHEMA)
    op.drop_table("submission_test_results", schema=SCHEMA)
    op.drop_table("submissions", schema=SCHEMA)
    op.drop_table("classroom_assignments", schema=SCHEMA)

    op.add_column(
        "test_cases",
        sa.Column(
            "is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        schema=SCHEMA,
    )
    # An edge Test Case comes back as hidden (ADR-0008).
    op.execute("UPDATE core.test_cases SET is_hidden = (kind <> 'sample')")
    # The default only filled existing rows; the original column had none.
    op.alter_column("test_cases", "is_hidden", server_default=None, schema=SCHEMA)
    op.drop_constraint("ck_test_cases_kind", "test_cases", schema=SCHEMA, type_="check")
    op.drop_column("test_cases", "note", schema=SCHEMA)
    op.drop_column("test_cases", "kind", schema=SCHEMA)

    op.drop_table("assignment_versions", schema=SCHEMA)
    op.drop_column("assignments", "show_hidden_names", schema=SCHEMA)
    op.drop_column("assignments", "language", schema=SCHEMA)
    op.drop_column("assignments", "time_limit_ms", schema=SCHEMA)
    op.drop_column("assignments", "current_version", schema=SCHEMA)
    op.drop_column("assignments", "owner_id", schema=SCHEMA)
    op.drop_column("assignments", "topic_id", schema=SCHEMA)

    op.drop_table("classroom_members", schema=SCHEMA)
    op.drop_table("classrooms", schema=SCHEMA)

    op.drop_table("instructor_requests", schema=SCHEMA)
    op.drop_table("sessions", schema=SCHEMA)
    op.drop_table("email_verification_tokens", schema=SCHEMA)

    op.drop_column("users", "last_active_at", schema=SCHEMA)
    op.drop_column("users", "is_active", schema=SCHEMA)
    op.drop_column("users", "email_verified_at", schema=SCHEMA)
    op.drop_column("users", "password_hash", schema=SCHEMA)
    op.alter_column(
        "users",
        "full_name",
        new_column_name="display_name",
        type_=sa.String(),
        nullable=True,
        schema=SCHEMA,
    )
    op.alter_column("users", "role", server_default=None, schema=SCHEMA)
    # Students have no place in the old role set; the downgrade refuses to
    # guess what they should become.
    op.drop_constraint("ck_users_role", "users", schema=SCHEMA, type_="check")
    op.create_check_constraint(
        "ck_users_role", "users", "role IN ('instructor', 'admin')", schema=SCHEMA
    )
